AWSTemplateFormatVersion: 2010-09-09
Description: Create VPC 

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          Default: "PJPrefix"
        Parameters:
          - PJPrefix
      - Label:
          Default: Network Layer Configuration 
        Parameters:
          - AvailabilityZone
          - VPCCIDR 
          - PublicSubnet1aCIDR
          - PublicSubnet1cCIDR
          - PrivateSubnet1aCIDR
          - PrivateSubnet1cCIDR
          - PublicSubnetName
          - PrivateSubnetName

    ParameterLabels:
      AvailabilityZone:
        Default: AvailabilityZone
      VPCCIDR:
        Default: VPC CIDR 
      PublicSubnet1aCIDR:
        Default: PublicSubnet1a CIDR
      PublicSubnet1cCIDR:
        Default: PublicSubnet1c CIDR
      PrivateSubnet1aCIDR:
        Default: PrivateSubnet1a CIDR
      PrivateSubnet1cCIDR:
        Default: PrivateSubnet1c CIDR
      PublicSubnetName:
        Default: PublicSubnetName
      PrivateSubnetName:
        Default: PrivateSubnetName

Parameters:
  PJPrefix:
    Type: String
    Default: "lalala"

  AZa:
    Type: String 
    Default: ap-northeast-1a

  AZc:
    Type: String 
    Default: ap-northeast-1c

  VPCCIDR:
    Type: String
    Default: 10.0.0.0/16
    
  PublicSubnet1aCIDR:
    Type: String
    Default: 10.0.10.0/24

  PublicSubnet1cCIDR:
    Type: String
    Default: 10.0.20.0/24

  PrivateSubnet1aCIDR:
    Type: String
    Default: 10.0.30.0/24

  PrivateSubnet1cCIDR:
    Type: String
    Default: 10.0.40.0/24

  PublicSubnetName:
    Type: String
    Default: pubsub-1

  PrivateSubnetName:
    Type: String
    Default: prisub-1


Resources: 
#--------------------------------
# VPC
#--------------------------------
  lalalaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR 
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-vpc

#--------------------------------------------
# パブリックサブネット(ELB作成のため2つ必要 1a/1c)
#--------------------------------------------
  lalalaPublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZa 
      CidrBlock: !Ref PublicSubnet1aCIDR
      VpcId: !Ref lalalaVPC # Required
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-${PublicSubnetName}a

  lalalaPublicSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AvailabilityZone}c
      CidrBlock: !Ref PublicSubnet1cCIDR
      VpcId: !Ref lalalaVPC # Required
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-${PublicSubnetName}c

#------------------------------------------------------------
# プライベートサブネット(RDSサブネットグループ作成のため2つ必要 1a/1c)
#------------------------------------------------------------
  lalalaPrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AvailabilityZone}a
      CidrBlock: !Ref PrivateSubnet1aCIDR
      VpcId: !Ref lalalaVPC # Required      
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-${PrivateSubnetName}a

  lalalaPrivateSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub ${AvailabilityZone}c
      CidrBlock: !Ref PrivateSubnet1cCIDR
      VpcId: !Ref lalalaVPC # Required      
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-${PrivateSubnetName}c

#---------------------------
# インターネットゲートウェイ
#---------------------------
  lalalaIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-igw

#インターネットゲートウェイをVPCにアタッチ
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref lalalaVPC # Required
      InternetGatewayId: !Ref lalalaIGW

#--------------------------------------
# パブリックサブネットのルートテーブルを作成
#--------------------------------------
  lalalaRouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref lalalaVPC # Required
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-rt-pub

#ルート先にIGWを定義
  lalalaRoutePublic:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref lalalaIGW
      RouteTableId: !Ref lalalaRouteTablePublic # Required
 
#ルートテーブルをパブリックサブネットに関連付け
  PublicSubnetRouteTableAssociation1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref lalalaRouteTablePublic # Required
      SubnetId: !Ref lalalaPublicSubnet1a # Required

  PublicSubnetRouteTableAssociation1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref lalalaRouteTablePublic # Required
      SubnetId: !Ref lalalaPublicSubnet1c # Required


Outputs:
  VPCId:
    Value: !Ref lalalaVPC
    Export: 
      Name: VPCId 

  PublicSubnet1aId:
    Value: !Ref lalalaPublicSubnet1a
    Export: 
      Name: PublicSubnet1aId

  PublicSubnet1cId:
    Value: !Ref lalalaPublicSubnet1c
    Export: 
      Name: PublicSubnet1cId

  PrivateSubnet1aId:
    Value: !Ref lalalaPrivateSubnet1a
    Export: 
      Name: PrivateSubnet1aId 

  PrivateSubnet1cId:
    Value: !Ref lalalaPrivateSubnet1c
    Export: 
      Name: PrivateSubnet1cId

    