AWSTemplateFormatVersion: 2010-09-09
Description: Create VPC 

Resources: 
#VPC
  lalalaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: lalala-vpc

#パブリックサブネット(ELB作成のため2つ必要)
  lalalaPublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref lalalaVPC # Required
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: lalala-pubsub-1a

  lalalaPublicSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.16.0/24
      VpcId: !Ref lalalaVPC # Required
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: lalala-pubsub-1c

#プライベートサブネット(RDSサブネットグループ作成のため2つ必要)
  lalalaPrivateSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.128.0/24
      VpcId: !Ref lalalaVPC # Required      
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: lalala-prisub-1a

  lalalaPrivateSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.144.0/24
      VpcId: !Ref lalalaVPC # Required      
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: lalala-prisub-1c

#インターネットゲートウェイ
  lalalaIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: lalala-igw

#インターネットゲートウェイをVPCにアタッチ
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref lalalaVPC # Required
      InternetGatewayId: !Ref lalalaIGW

#パブリックサブネットのルートテーブルを作成
  lalalaRouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref lalalaVPC # Required
      Tags:
        - Key: Name
          Value: lalala-rt-pub

#ルートの設定(パブリックサブネット)
  lalalaRoutePublic:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref lalalaIGW
      RouteTableId: !Ref lalalaRouteTablePublic # Required
 
#ルートテーブルをパブリックサブネットに関連付け
  PublicSubnetRouteTableAssociation1a:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref lalalaRouteTablePublic # Required
      SubnetId: !Ref lalalaPublicSubnet1a # Required

  PublicSubnetRouteTableAssociation1c:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref lalalaRouteTablePublic # Required
      SubnetId: !Ref lalalaPublicSubnet1c # Required


Outputs:
  VPCId:
    Value: !Ref lalalaVPC
    Export: 
      Name: VPCId 

  PublicSubnet1aId:
    Value: !Ref lalalaPublicSubnet1a
    Export: 
      Name: PublicSubnet1aId

  PublicSubnet1cId:
    Value: !Ref lalalaPublicSubnet1c
    Export: 
      Name: PublicSubnet1cId

  PrivateSubnet1aId:
    Value: !Ref lalalaPrivateSubnet1a
    Export: 
      Name: PrivateSubnet1aId 

  PrivateSubnet1cId:
    Value: !Ref lalalaPrivateSubnet1c
    Export: 
      Name: PrivateSubnet1cId

    