AWSTemplateFormatVersion: 2010-09-09
Description: Create ELB 

Parameters:
  PJPrefix:
    Type: String
    Default: "lalala"

Resources: 
#ELB(ALB)
  lalalaELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Scheme: internet-facing #内部向けかインターネット向けか
      SecurityGroups:
        - !ImportValue SGEC2Id
      Subnets:
        - !ImportValue PublicSubnet1aId
        - !ImportValue PublicSubnet1cId
      Tags:
        - Key: Name
          Value: !Sub ${PJPrefix}-elb
      Type: application 

#ELBターゲットグループ
  lalalaELBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP 
      ProtocolVersion: HTTP1
      Tags:
        - Key: Name 
          Value: !Sub ${PJPrefix}-elb-tg
      TargetType: instance 
      Targets:
        - Id: !ImportValue EC2Instance1aId
      VpcId: !ImportValue VPCId

#ELBリスナー
  lalalaELBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: # Required
        - TargetGroupArn: !Ref lalalaELBTargetGroup
          Type: forward #forwardは指定されたターゲットグループにリクエストを送信
      LoadBalancerArn: !Ref lalalaELB # Required
      Port: 80
      Protocol: HTTP 


Outputs:
  ELBId:
    Value: !Ref lalalaELB
    Export: 
      Name: ELBId

  